version: "3.8"
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: aidynfatikh/todo-back:latest
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: aidynfatikh/todo-front:latest
    ports:
      - "3000:80"
    depends_on:
      - back

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
